### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by yikeshangweng** [deeround/jdbc-plus#1]
sql 语句     select count(*) from t_user  where username=?  and age=? 

  //查询汇总
  if (localPage.isCount()) {
      Object cnt = jdbcTemplate.queryForMap(dialect.getCountSql(sql)).get("PG_COUNT");
      localPage.setTotal(Long.parseLong(cnt.toString()));
  }

 上面代码  是不是不能处理 带有“？” 的sql 语句，可以给联系方式吗

**Comment by deeround** [comment]
已解决
