### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by yikeshangweng** [deeround/jdbc-plus#2]
demo 中 给出的如下例子
 
        PageHelper.startPage(2, 2);
        List<Map<String, Object>> list = this.jdbcTemplate.queryForList("select * from test_user");
        //最终执行SQL：select * from test_user LIMIT 2，2
        PageInfo<Map<String, Object>> page = new PageInfo<>(list);
        //PageInfo对象包含了分页信息（总行数等）
        return page;

如果返回的是
 List<XXX> bean=jdbcTemplate.query(sql, new BeanPropertyRowMapper<(XXX.class),object...args);

//查询汇总
if (localPage.isCount()) {
    Object cnt = jdbcTemplate.queryForMap(dialect.getCountSql(sql), methodInfo.getParameters()).get("PG_COUNT");
    localPage.setTotal(Long.parseLong(cnt.toString()));
}

methodInfo.getParameters() 返回是null 程序直接报错

请作者慎重考虑各种常用情况。

**Comment by deeround** [comment]
感谢反馈，现已处理，在文档中【JdbcTemplate支持】部分对支持的方法做了描述。
